### ISSUE TITLE
To change my entry I have to unpublish the current version

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#1]
If I need to change one of my entries you require me to unpublish it, and until you approve my changes any visitors to Open Exchange won't find the old version of my entry. Please fix this.

**Comment by evshvarov** [comment]
John, thanks for reporting this. It is sensible and we'll put it in a queue.

**Comment by MakarovS96** [comment]
Hi, John! We added the ability to change your packages without unpublishing in the actual release. Please, check it.

**Comment by evshvarov** [comment]
@gjsjohnmurray John! Could you please close it? We did it eventually )

**Comment by gjsjohnmurray** [comment]
Tested OK. Thanks!
