### ISSUE TITLE
Issues tab not showing correctly

### ISSUE THREAD

**Issue by amirsamary** [intersystems-community/openexchange#100]
We have an issues tab for an application that shows the current list of open issues on GitHub. Here is my current list of issues for the HTAP Demo:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/6372644/72380816-3225c180-36e4-11ea-9996-7ea005bcdcab.png">

The problem is that on open exchange this appears like this:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/6372644/72380830-3d78ed00-36e4-11ea-88d8-b912d6cf3db1.png">

**Comment by evshvarov** [comment]
Thanks, Amir!
Is it a mobile device?

вт, 14 янв. 2020 г. в 23:41, Amir Samary <notifications@github.com>:

**Comment by gnibeda** [comment]
Got it, thanks. Will be fixed in next release

**Comment by amirsamary** [comment]
No. It’s Safari, on my Mac.
