### ISSUE TITLE
The bug with image uploading

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#106]
I was trying to upload an image in a Published App.

In the DevTools console I got the error: 

POST https://openexchange.intersystems.com/mpapi/packages/image/446 500 (Internal Server Error)

Using the Network tab, I could see the details in the Response: 
```
{
    "errors":[ {
            "code":5001,
            "domain":"%ObjectErrors",
            "error":"ERROR #5001: You can't to change title image of the published package. Please, unpublish package or create draft.",
            "id":"GeneralError",
            "params":["You can't to change title image of the published package. Please, unpublish package or create draft."
            ]
        }
    ],
    "summary":"ERROR #5001: You can't to change title image of the published package. Please, unpublish package or create draft."
}
```
As a suggestion, this response could be shown in a toast message? 

Reported by @diashenrique

**Comment by evshvarov** [comment]
The post on community: https://community.intersystems.com/post/how-publish-application-intersystems-open-exchange#comment-115226

**Comment by MakarovS96** [comment]
"Upload image" button should be hidden for published packages. I created this message if anyone would try to upload an image manually. @gnibeda can you hide that button for published packages?
