### ISSUE TITLE
should correctly show repo's images from readme

### ISSUE THREAD

**Issue by daimor** [intersystems-community/openexchange#12]
as an example
https://openexchange.intersystems.com/package/VSCode-ObjectScript
and original
https://github.com/daimor/vscode-objectscript/blob/master/README.md

**Comment by gnibeda** [comment]
This is caused by relative paths of images. e.g. `images/screenshot.png`.
You can change it to absolute path to fix it. 

Soon, I'll implement url rewriting during readme parsing to fix issue with relative paths.

**Comment by daimor** [comment]
I see, but my suggestion is to have implemented such rewriting.

**Comment by evshvarov** [comment]
@daimor , if it works?
