### ISSUE TITLE
Lowercase Readme Doesn't Pick Up

### ISSUE THREAD

**Issue by nikitaeverywhere** [intersystems-community/openexchange#13]
Hello!

Just filing a friendly issue to let you know that StackExchange doesn't pick up lowercase `readme.md`. Example: https://openexchange.intersystems.com/package/WebTerminal

It would be nice to fix this! Thanks!

**Comment by eduard93** [comment]
https://developer.github.com/v3/repos/contents/#get-the-readme

**Comment by evshvarov** [comment]
Thanks @eduard93 . @ZitRos, I think it is wise to follow Github guidelines. Thoughts?

**Comment by nikitaeverywhere** [comment]
@eduard93 wait, so what?

`curl -i https://api.github.com/repos/intersystems-community/webterminal/readme`

```
{
  "name": "readme.md",
  "path": "readme.md",
  "content": "---PROPERLY ENCODED BASE64 README---"
  ...
}
```

Or you just suggesting this for developers, are you?

@evshvarov all GitHub guidelines are followed as far as GitHub displays the readme.

**Comment by eduard93** [comment]
I'm suggesting that developers should use this API to retrieve readme contents.

**Comment by evshvarov** [comment]
@ZitRos, don't see any 'readme.md' or 'readme.MD' in the docs API, only README.md. I think we better follow GIthub API in this case

**Comment by evshvarov** [comment]
@ZitRos , should we close this?

**Comment by nikitaeverywhere** [comment]
Was the webterminal readme fixed?

**Comment by evshvarov** [comment]
@ZitRos we decided to not support other cases then README.md form. So, if it is README.md in webterminal it will work automatically

**Comment by nikitaeverywhere** [comment]
I want to make a pull request then :/ May I? :)

**Comment by evshvarov** [comment]
Why not change the file to README.md?

**Comment by nikitaeverywhere** [comment]
If you say that you pick the readme from GitHub the user assumes that it
will get what GitHub displays... GitHub displays multiple readme formats.

I always use lowercase readme in my projects and I see that other people
even use other formats of a readme file, like txt or other markdown
languages, through *.md format is just the most popular.

Canonically, at first, we have to request GitHub and find out what’s the
readme file and then request the file itself, unlike I suppose we do now —
request strictly README.md.

Because in the other scenario you are forcing users to strictly name their
readme files, which is equal to introducing a new standard which is not
acceptable.

**Comment by evshvarov** [comment]
make a PR?

**Comment by nikitaeverywhere** [comment]
@evshvarov I would love to, however, I assume your repo is private.

**Comment by gnibeda** [comment]
done(also for licenses)

**Comment by nikitaeverywhere** [comment]
❤️

**Comment by nikitaeverywhere** [comment]
Thanks Anton!! Does it parse readme file in realtime or during the submission procedure?

**Comment by gnibeda** [comment]
In realtime, always real readme from repo would be taken.

**Comment by evshvarov** [comment]
@ZitRos do you want to close the task?

**Comment by nikitaeverywhere** [comment]
@gnibeda I was wondering then why the readme isn’t the GitHub’s one [here](https://openexchange.intersystems.com/package/WebTerminal)

**Comment by gnibeda** [comment]
Readme was taken though api: https://api.github.com/repos/intersystems-community/webterminal/contents/readme.md?ref=master
For me it looks similar. Which differences you faced up?

**Comment by nikitaeverywhere** [comment]
Hm. Maybe I don’t see the actual readme on the mobile device
