### ISSUE TITLE
Introduce "fresh" indicators

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#142]
Last commit on Github
Last release on OEX

And filter: 1 month, 6, months, 1 year, all 
for both

**Comment by Lena-Ev** [comment]
В филтре сделать **радио баттон,** одиночный выбор
<img width="567" alt="image" src="https://user-images.githubusercontent.com/77621970/162914761-3694b57b-00e4-4ca3-a701-237db373d1cc.png">

**Comment by Lena-Ev** [comment]
Сделать только Last release

**Comment by gnibeda** [comment]
Done on FE side, BE implementation needed

**Comment by MakarovS96** [comment]
добавился новый параметр fresh=[-1,0,1,6,12]
-1 - больше года
0 - показывать все
1,6,12 - количество месяцев
предлагаю сделать радио потому что не понятно по какому принципу фильтровать в чеке

**Comment by Lena-Ev** [comment]
- [ ] В филтре сделать радио баттон, одиночный выбор
