### ISSUE TITLE
Local links in .md files not working

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/openexchange#143]
When OpenExchange picks up a readme.md file from a GH repo, it does not "fix" the local links in there. For example, when clicking "data transfer docs" halfway down the https://openexchange.intersystems.com/package/PythonGateway page, it comes back with a 404. Simply adding a base URL for the "imported" .md contents perhaps shouldn't be too hard?

**Comment by Lena-Ev** [comment]
https://github.com/intersystems-community/openexchange/issues/211

**Comment by Lena-Ev** [comment]
Links and images imported from GitHub via MD file nnow are displayed in application description  
https://community.intersystems.com/post/open-exchange-march-2021-release

**Comment by gjsjohnmurray** [comment]
This is still broken for me.

See how OEX imported https://raw.githubusercontent.com/intersystems-community/intersystems-servermanager/master/README.md into https://openexchange.intersystems.com/package/Server-Manager-for-VSCode

**Comment by MakarovS96** [comment]
Done
