### ISSUE TITLE
Image URL field broken

### ISSUE THREAD

**Issue by lscalese** [intersystems-community/openexchange#144]
Hi,

I have a trivial problem with open exchange.

You can see on this page https://openexchange.intersystems.com/package/JSON-Web-Token-Generator the image is not shown.

When I edit the application, image url field contain /mp/img/packages/621/icon.svg.

I attempt to update the image URL by https://jwt.io/img/icon.svg and save, but when I edit again the image URL is reset to /mp/img/packages/621/icon.svg.

Thank you.
Lorenzo.

**Comment by MakarovS96** [comment]
Now we use only image uploading before send for approval. You can choose "Upload image" option in "Settings" menu.
![image](https://user-images.githubusercontent.com/19629483/88000533-31f9f900-cb41-11ea-8564-1205107d31ef.png)
