### ISSUE TITLE
Logo URL broken a while after edit application

### ISSUE THREAD

**Issue by daimor** [intersystems-community/openexchange#145]
Edited my app VSCode-ObjectScript, changed a couple of fields, except Logo URL.
When saved, it was good, but after a few refreshes, logo disappeared, and the field contains now wrong value. 
original URL, supposed to be
https://raw.githubusercontent.com/intersystems-community/vscode-objectscript/master/images/logo.png
but after a while it contains
/mp/img/packages/641/logo.png
and this URL does not work

**Comment by MakarovS96** [comment]
Done. Please check
