### ISSUE TITLE
Application stuck in 'On approval' state

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#155]
There seems to be a problem with Serenji's entry at OpenExchange. On 4th June edited it, sent it for approval, set version number 3.1.3 and entered the info about what changed. I received an email saying it was published. But the hyperlink in the email is to https://openexchange.intersystems.com/package/Serenji-2 and that page still shows as "On approval".

When I use a private browser window (so I'm not logged in) and search for Serenji at OE I get https://openexchange.intersystems.com/package/Serenji which reports "Published", but is still 3.1.1. Strangely the "Last updated" date is the day I submitted 3.1.3 for approval and was notified of the approval (2020-06-04).

From a logged-in browser I use Applications from the Profile menu and see two Serenji entries:

![image](https://user-images.githubusercontent.com/6726799/84504711-50ecac00-acb4-11ea-9a3c-320cad71ea12.png)

The package name for the "On approval" one is Serenji-2.

**Comment by MakarovS96** [comment]
Done!

**Comment by gjsjohnmurray** [comment]
Thanks
