### ISSUE TITLE
Fix markdown preview css issues

### ISSUE THREAD

**Issue by tsafin** [intersystems-community/openexchange#158]
CSS used for rendering repositories markdown is awkward:
- it upscales every images to 100% column width (regardless of a size, even very tiny image)
- and it uses random sizes for code, and headings.

Could you please make sure that rendering markdown of a selected package will look similar to the Github?

e.g. compare size of buttons, images, and code size on https://openexchange.intersystems.com/package/BlocksExplorer-1?tab=details vs https://github.com/daimor/BlocksExplorer/blob/master/README.md

![openexchange-preview](https://user-images.githubusercontent.com/4956130/87585493-d1edf780-c6e7-11ea-9daa-43479a68de11.png)
_versus_
![github-preview](https://user-images.githubusercontent.com/4956130/87585496-d31f2480-c6e7-11ea-976d-09813c60df15.png)

**Comment by MakarovS96** [comment]
Fixed. Please check
