### ISSUE TITLE
Change ZPM package for OEX 

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/openexchange#160]
I try to give my ZPM package a more meaningful name.
changed it in modul.xml,edit+save in  OEX project,
All looks fine. OEX shows me zmp "install  nename."
Get positive confirmation mail from OEX
10 min. later negative msg from ZPM: package already registered with a different name. 
no changes in ZPM.
zpm search  confirms the old name is still there but OEX is showing the new (wrong) name.

What is the correct sequence to execute such change?

**Comment by evshvarov** [comment]
Hi @rcemper ! We intentionally don't have rename functionality yet. and delete functionality - because its complicated and risky. We can delete the package by your request (name the package) and next release will publish the new one. Say what package we need to delete?

**Comment by rcemper** [comment]
Hmm. I understand. This could cause quite some complications.
Meanwhile, I returned to the old name. and that should work.
It is just less intuitive:
I'll come back in case of urgency. 
Important to me;  It is not there and I didn't over-read it

**Comment by evshvarov** [comment]
We hope the package rename is not an often procedure. It can cause
problems: people will install it in their projects, use as dependencies.
