### ISSUE TITLE
Indents on the project page

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/openexchange#163]
Make equal indents.

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/25077319/88537808-e6e75680-d016-11ea-9595-16e41d9edd4a.png">

**Comment by gnibeda** [comment]
indents are equal. you see some differences because of how browser renders text blocks:
![block](https://user-images.githubusercontent.com/9804674/88819242-6700ee00-d1c8-11ea-8b69-ef4a8fc1f3aa.png)
as you can see, there is some empty space on top and bottom. but margins between blocks are equal

**Comment by dyubaylo97** [comment]
Ok. Thanks!
