### ISSUE TITLE
Fix the Contest link preview

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/openexchange#167]
The Contest link preview shows the logo of the old app.

https://openexchange.intersystems.com/contest/current 

![image](https://user-images.githubusercontent.com/25077319/90894462-4c85f300-e3c9-11ea-933c-7ff1bdae8596.png)

**Comment by MakarovS96** [comment]
``` html
<meta property="og:title" content="Text"> 
<meta property="og:description" content="Text"> 
<meta property="og:image" content="http://example.com/thumbnail.jpg">
``` 
Meta tags to set default image to preview. 
- For companies it should be company image or default package icon. 
- For packages - package image or default package icon. 
- For other pages it should be OEX logo.

**Comment by gnibeda** [comment]
done on dev and stage
