### ISSUE TITLE
Update InterSystems product names in the app editor

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/openexchange#168]
Make the following changes in Application Editor:

InterSystems Technology:
- InterSystems IRIS
- InterSystems IRIS for Health
- HealthShare
- TrackCare
- Caché
- Ensemble
- InterSystems Analytics (DeepSee)
- InterSystems Text Analytics (iKnow)

[Use this order of products in the drop-down list].

**Comment by MakarovS96** [comment]
How should I change the HealthConnect category? Maybe are we need to merge this category with HealthShare?

**Comment by dyubaylo97** [comment]
Yes, we can merge HealthShare and Health Connect.
