### ISSUE TITLE
Add the documentation on how to change the application

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#170]
If you want to make publish changes to your application, e.g. the name, description or image do the following:
1. Open the page of the application and click Edit:
<img width="1114" alt="Screenshot 2020-09-08 at 10 27 43" src="https://user-images.githubusercontent.com/2781759/92446100-fe8d2f80-f1bd-11ea-93ee-290614f9f24f.png">
This will create a new draft of your application and opens Application Editor.
2. Make the updates to your application, Check with Preview, and once you good click Save:
<img width="1108" alt="Screenshot 2020-09-08 at 10 30 14" src="https://user-images.githubusercontent.com/2781759/92446335-588df500-f1be-11ea-8e06-1dc72fe4e5c8.png">
This will save the draft application which you can send for publishing with the next step. You still able to make changes to the description, tags, etc or change the icon of the app.
3. If you want to change the icon of the app open the Settings menu and click "Upload an image"
<img width="1079" alt="Screenshot 2020-09-08 at 10 33 23" src="https://user-images.githubusercontent.com/2781759/92446658-cfc38900-f1be-11ea-8221-11af8a213f7c.png">
This will let you upload a new image for your application icon from your computer. 
4. Once you are good with application changes or/and new icon you can send the changes for approval. 
<img width="1075" alt="Screenshot 2020-09-08 at 10 36 52" src="https://user-images.githubusercontent.com/2781759/92446967-4c566780-f1bf-11ea-9899-3f6abff443a0.png">
InterSystems managers will review the new changes and once the application is approved it will change the published one with new updates

**Comment by dyubaylo97** [comment]
**How to make changes to a published application?**

If you want to make changes to your application, e.g. name, description or image, you need to do the following:

1. Open the application page and click the “Edit” button in the Settings menu:
SCREENSHOT
This will create a new draft of your application and open the Application Editor.

2. Make the updates to your application, сheck with the “Preview” button, and once you good, click the “Save” button:
SCREENSHOT
This will save a draft of your application, which you can submit for publication in the next step.
_Note_: You can still make changes to the description, tags, etc., or change the app logo.

3. If you want to change the application logo, open the Settings menu and select the "Upload image" section.
SCREENSHOT
This will allow you to upload a new image for your application logo from your computer.

4. Once you've finished making changes to the app and/or uploading a new logo, you can submit your changes for approval with the “Send for approval” button.
SCREENSHOT
Your application will be reviewed and approved by OEX managers, and then will be published with all updates.

**Comment by MakarovS96** [comment]
In next release. Done
