### ISSUE TITLE
Build a Tag cloud menu

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#177]
Page with all the tags

**Comment by Lena-Ev** [comment]
после того как поменяем теги
1 - запись тегов через запятую (может. решетку)
2. когда юзер пишет тег - предлагать ему теги похожие (начинающиеся с тех же символов) - как в инсте, когда ставишь теги, и он может выбрать что-то из списка или поставить свой

**Comment by Lena-Ev** [comment]
- [ ] rest который вернет список всех тегов @MakarovS96 
- [x] система подсказки @gnibeda

**Comment by MakarovS96** [comment]
/packages/tags GET Антон уже использует этот запрос

**Comment by Lena-Ev** [comment]
@MakarovS96  добавить количество тегов в рест

**Comment by MakarovS96** [comment]
/packages/tags GET
[{tag:str, count:int}, ...]

**Comment by Lena-Ev** [comment]
уточнить у жени как он это видит

**Comment by Lena-Ev** [comment]
https://www.mongodb.com/community/forums/tags
https://github.community/tags

**Comment by Lena-Ev** [comment]
https://github.community/tags - @gnibeda сделать как на этом сайте, без группировки
Заголовок 
Tags

**Comment by Lena-Ev** [comment]
- [ ] 1

<img width="187" alt="image" src="https://user-images.githubusercontent.com/77621970/168782954-3c4d5b2b-b0ed-4fd0-b3a1-014655427d9a.png">

добавить сортировку можно быстро или надо рест еще от Семена?

только нашим компонентом с сортировкой:
То есть в место applications - Tags
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/77621970/168783283-bcc8f647-ff75-4f54-b92c-95f3782b6e36.png">

- [x] 2
по клику на тег появляется вот такая страница без приложений с этим тегом:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/77621970/168785888-80bc6e49-9f02-4c7e-817f-31c498f5d110.png">

**Comment by Lena-Ev** [comment]
осталось сделать сортировку (по такому типу - только вместо applications - tags


![Image](https://user-images.githubusercontent.com/77621970/169521534-9cdf2ac3-9e40-4957-8ad8-0ce11d9e4677.png)

**Comment by Lena-Ev** [comment]
поправить расстояние от меню - сделать как тут:


![Image](https://user-images.githubusercontent.com/77621970/169985942-e7ff68f1-0e2b-4366-8553-1a33c6adfd3e.png)



![Image](https://user-images.githubusercontent.com/77621970/169985996-b33c1c5b-c412-40ef-9060-69c662d78b63.png)

**Comment by Lena-Ev** [comment]
На ОЕХ с ПД убрать
