### ISSUE TITLE
YouTube Video Links Format

### ISSUE THREAD

**Issue by nikitaeverywhere** [intersystems-community/openexchange#18]
Greetings!

During the new upload, I've noticed that if you insert a link of, say, `https://www.youtube.com/watch?v=2l_btAGu_dA&list=PLKb2cBVphNQSzuCyRo3N3KAbSTDhpnDYY&index=5` format, the embedded video won't play. The links to videos which appear in the iframe should have this format: `https://www.youtube.com/embed/2l_btAGu_dA`, where `2l_btAGu_dA` is the ID of the video

Good work so far. Cheers!

**Comment by gnibeda** [comment]
done
