### ISSUE TITLE
Add a link to digital services in application approval email

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#194]

**Comment by olgazavrazhnova** [comment]
[ @MakarovS96  let's discuss how to implement this in a most easy and effective way ]

In the application approval email (where we notify that a application successfully published) - add a button  "Promote my application". 

After user clicked on this button:
1) a task should be created in OEX Workflow for Olga Zavrazhnova (olga.zavrazhnova_ctr@intersystems.com) and Evgenia Kurbanova (kurbash@mail.ru), who will be responsible to contact that person to offer current promotional options (digital services). 
2) Also a user should receive a notification that we will contact him shortly to offer our promotional options.

**Comment by Lena-Ev** [comment]
outdated, there is a newsletter about services after a company is published (planned)
