### ISSUE TITLE
What are the requirements for the image in order to fit well

### ISSUE THREAD

**Issue by drechema** [intersystems-community/openexchange#2]
I set this URL for my app icon image:
[https://github.com/drechema/iris-nodejs/raw/master/iris-nodejs.png](https://github.com/drechema/iris-nodejs/raw/master/iris-nodejs.png)
The image look fine in the app edition but not in the app list...

**Comment by evshvarov** [comment]
Today the best idea is to introduce image in csr (vector format).
@MakarovS96 , do you know what is the best ratio for the image if it is not a csr?

**Comment by evshvarov** [comment]
Hi @drechema !
The height is 54 px, the width not more than 200px
