### ISSUE TITLE
Markdown Anchor Link

### ISSUE THREAD

**Issue by lscalese** [intersystems-community/openexchange#211]
Hi,

There is minor issue with title links in Readme.md file imported on OpenExchange.

Ex, link to a title : 
```
2. [Simple Http Client Sample](#Simple-Http-Client-Sample)

.... content ...

## Simple Http Client Sample  
```

On OEX, users are redirected to the main page.
I think, it could be fixed by adding a tag `<a>` on each title, ex: 

```
<h2>
<a id="Simple-Http-Client-Sample" href="#Simple-Http-Client-Sample"></a>
Simple Http Client Sample
</h2>
```

Lorenzo.

**Comment by Lena-Ev** [comment]
#143 issue is set up for this problem, task in the process

**Comment by gjsjohnmurray** [comment]
@Lena-Ev I think this was incorrectly marked as a duplicate of #143. Please reopen it.

**Comment by Lena-Ev** [comment]
We'll check!

**Comment by Lena-Ev** [comment]
done^ check pls on this app:
https://openexchange.intersystems.com/package/Config-API#Prerequisites
