### ISSUE TITLE
add Manage apps module to Developers' applications page

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#227]
To filter draft, on approval and published modules.

E.g. [here](https://openexchange.intersystems.com/profile/Evgeny%20Shvarov/PsVoekohQP54VMJhkXmYMe96mPo?tab=apps)
It's very difficult to find what is in draft, what is on approval and what is published when you have more than 10 apps

**Comment by Lena-Ev** [comment]
Now the apps are shown as a list which you can filter by many oarameters, as well as search by name

**Comment by Lena-Ev** [comment]
In filter
