### ISSUE TITLE
split brain in analytics

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/openexchange#233]
there is a rather fresh project added only last week.
https://openexchange.intersystems.com/package/FOREACH-for-ObjectScript

The counters show 4 downloads. but the graph knows only of 1
![lacibpleknngjamj](https://user-images.githubusercontent.com/31236645/108564802-f8ba7f00-7303-11eb-8356-a153f1e74014.png)

**Comment by Lena-Ev** [comment]
We fixed analytics syncing and now there is no difference but the data is updated evry 10 minutes
