### ISSUE TITLE
Fix Facebook icon

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/openexchange#237]
FB icon in Safari:
![image](https://user-images.githubusercontent.com/25077319/109514239-dddfcb80-7ab6-11eb-9d48-540c782eb5a7.png)

in Chrome:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/25077319/109514214-d7e9ea80-7ab6-11eb-8019-6752eca7fcb7.png">

**Comment by Lena-Ev** [comment]
@gnibeda  Can we try to exchange the image to another one ?
Doesn't look good on MacOs

**Comment by Lena-Ev** [comment]
Lets try this one
![icons8-facebook](https://user-images.githubusercontent.com/77621970/153447646-355f640c-82be-496b-be1f-b3ef0e48fe34.svg)
or this
![icons8-facebook 1](https://user-images.githubusercontent.com/77621970/153447783-b3d44155-e90e-4805-b30c-18f04df5fc2b.svg)
