### ISSUE TITLE
Application release notification email - Link to "Mute the notifications from this application" fails

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#240]
![image](https://user-images.githubusercontent.com/6726799/110331171-a9b85d80-8016-11eb-89c0-c6e1341a254b.png)

**Comment by gjsjohnmurray** [comment]
Please can this get resolved? :pray:

**Comment by MakarovS96** [comment]
I could not repeat the error. The mute link in the email is a one-time thing so it won't work when you use it again. Can you repeat this problem? If so, can you make a video or gif?

**Comment by MakarovS96** [comment]
If you want to unsubscribe from the app urgently, you can do so through your profile
![image](https://user-images.githubusercontent.com/19629483/111335892-79308d80-86c0-11eb-8db0-b66db2d7166a.png)

**Comment by gjsjohnmurray** [comment]
I get that message when I use the link from Firefox. This is because the response header specifies content-type: application/json but the response body is plaintext:
```
App subscription has been suspended
```

So you should either wrap the success message in JSON or else specify a different content-type.

By checking my 'Current subscription' page before and after my first click on the link I can see that the click did actually succeed.

If I click again I get the following cryptic response:
![image](https://user-images.githubusercontent.com/6726799/111339916-0eeffc80-8670-11eb-9ae9-571e2d404c66.png)

Presumably this happens because the first click unsubscribed me, or because the link becomes invalid after first use.

Maybe send the user a more meaningful plaintext response?

**Comment by MakarovS96** [comment]
Yes you're right, when you use the link again the error appears because you have already unsubscribed. About the fact that you get just text, we just have not prepared the UI for the mute application. When the UI is ready we will let you know. Please do not close the issue, it will be additional motivation)
