### ISSUE TITLE
Application logo it's not saving anymore.

### ISSUE THREAD

**Issue by diashenrique** [intersystems-community/openexchange#244]
First of all, I would like to congrats on the introduction of the new UI.

But when I submitted my application, I chose a custom image to be my logo app.  

When I saved it, the icon wasn't shown in the OpenExchange gallery. The icon turns back to the default image.

**Comment by MakarovS96** [comment]
Hi Henrique! Could you please attach your image to this issue?

**Comment by diashenrique** [comment]
1. Editing the application details
![Screen Shot 2021-05-31 at 13 23 04](https://user-images.githubusercontent.com/4448425/120220790-abf41780-c213-11eb-81c7-e119e8d145e6.png)

2. After saved the application
![Screen Shot 2021-05-31 at 13 23 17](https://user-images.githubusercontent.com/4448425/120220810-b6aeac80-c213-11eb-95b6-69996a9f86ce.png)

3. After sent it to approval
![Screen Shot 2021-05-31 at 13 23 44](https://user-images.githubusercontent.com/4448425/120220826-bca48d80-c213-11eb-92c9-094eb49e7f31.png)

PS: Sorry to submit for approval just to generate this step-by-step

**Comment by MakarovS96** [comment]
Thanks! I'm working on it.

**Comment by MakarovS96** [comment]
Can you attach the picture you use to install in the package? I checked and found a bug with the UI, but after reloading the page the picture appears.

**Comment by diashenrique** [comment]
![IRISonFHIR_OpenExchange](https://user-images.githubusercontent.com/4448425/120285816-059c2680-c294-11eb-8272-f71e465c5a8f.png)

**Comment by MakarovS96** [comment]
fixed
