### ISSUE TITLE
Round the value in Rating

### ISSUE THREAD

**Issue by diashenrique** [intersystems-community/openexchange#246]
I think that it would be nicer to have a rounded value here.

![Screen Shot 2021-06-21 at 17 40 14](https://user-images.githubusercontent.com/4448425/122825015-c4f26480-d2b7-11eb-9427-f823d108c101.png)

**Comment by eduard93** [comment]
One fractional digit should be enough.

**Comment by diashenrique** [comment]
Yes, I totally agree with you. Using this image as an example, a rating of 4.2 would be better.
