### ISSUE TITLE
search for zpm package on openexchange

### ISSUE THREAD

**Issue by daimor** [intersystems-community/openexchange#248]
collection-index-and-query

![image](https://user-images.githubusercontent.com/1212251/126272050-85647d79-7ed8-4b4f-8091-bdebb7168f2f.png)

Expected to find https://openexchange.intersystems.com/package/Collection-Indexing-and-Query

**Comment by evshvarov** [comment]
[image: Screenshot 2021-07-20 at 09.27.48.png]
You can narrow the search using ZPM checkbox

**Comment by daimor** [comment]
Which one?

![image](https://user-images.githubusercontent.com/1212251/126272586-e7fbf60b-9c5f-488e-808d-1aff1a4265f6.png)

**Comment by daimor** [comment]
what does it mean `automatic` in the parens?

**Comment by Lena-Ev** [comment]
now it searched by zpm package name
