### ISSUE TITLE
tab to search support in browser

### ISSUE THREAD

**Issue by daimor** [intersystems-community/openexchange#249]
I'd like to have the ability to search on openexchange without opening the site, right from the address bar, without manually adding it there.
It works for DC
![image](https://user-images.githubusercontent.com/1212251/127117424-7c3460fd-50fc-4db4-bc01-003848d02db7.png)

This documentation could be a point to start for realization this
https://www.chromium.org/tab-to-search

**Comment by Lena-Ev** [comment]
works for me, could you check pls
