### ISSUE TITLE
Application editor doesn`t allow to edit Short description

### ISSUE THREAD

**Issue by jakcpto** [intersystems-community/openexchange#250]
There is some bug while editing application.
Text in Short Description is able to be relaced by empty symbol or deleted entirely, but I can't replace symbol or add something.

https://user-images.githubusercontent.com/41373877/132137854-f79f1708-2a11-4305-aca1-4d693e7f29c3.mp4

**Comment by Lena-Ev** [comment]
Hello!
We tride to replicate the issue but it worked for us.
Could you try to do that in incognito mode and let us know if the issue still occure?
