### ISSUE TITLE
Missing review

### ISSUE THREAD

**Issue by lscalese** [intersystems-community/openexchange#253]
Hi,

I noticed a missing review on the application page.
On my reviews page (from the profile), I see a review from Sergei Mihaylenko for [config-copy](https://openexchange.intersystems.com/package/config-copy), but it does not appear on [application page](https://openexchange.intersystems.com/package/config-copy?tab=reviews).  

Also, I noticed there is access denied to the profile of [Sergei Mihaylenko](https://community.intersystems.com/user/sergei-mihaylenko).

**Comment by Lena-Ev** [comment]
Thank you for your feedback!
Fixed, you saw a draft of the review, no you will see it only when it will published.
