### ISSUE TITLE
Company member unable to publish their app on behalf of the company

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#254]
Doc at https://docs.openexchange.intersystems.com/company/solutions/ says I should find an "Add an Application" button, but it's not there.

Some of my apps are correctly showing as published by my company, but one of them (Serenji) isn't. I'm pretty sure it used to be correct. Maybe a recent edit which I submitted and which got approved has detached it from the list of company apps.

https://openexchange.intersystems.com/company/George-James-Software

Screenshots seem to be outdated in other ways, so maybe the procedure has changed. Please improve the docs here.

**Comment by Lena-Ev** [comment]
FIxed, now you can edit the app and it will not be detached from the company.
