### ISSUE TITLE
Updating an entry without incrementing version number is clunky and non-obvious

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#255]
After editing an entry (e.g. to fix a typo) it has to be sent for approval. The form for this pre-fills a higher version number and requires release notes.

Apparently if we don't want to bump the version number we can set new version number to be identical to existing one, but we must also re-enter the release notes of the existing release exactly, otherwise our previously-published release notes will get changed. I can understand the value of this (e.g. fixing a typo in release notes of currently-published version), but in that case please pre-fill the release notes field with what is on file. That way if we don't want to change anything there we can just click OK.

**Comment by Lena-Ev** [comment]
Now after making any changes in the app description you will be asked if this is a new release or just corrections.
In the second case you wouldn't need to fill in the Release form.
