### ISSUE TITLE
Saving a change to a company app doesn't let me publish it on behalf of the company

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#257]
FIxed, now you can edit the app and it will not be detached from the company.

_Originally posted by @Lena-Ev in https://github.com/intersystems-community/openexchange/issues/254#issuecomment-950922067_

I just tried to add a tag to our Serenji app, but only got this far:

![image](https://user-images.githubusercontent.com/6726799/141287061-c05b0cc1-b46b-431c-ae21-76c205c3463d.png)

Second option offers me the chance to create a new company, but not to choose my existing one, George James Software.

**Comment by Lena-Ev** [comment]
Thank you! We will check and come back.

**Comment by Lena-Ev** [comment]
Hey John!
We added your tags and the bug is fixed will work after next release.
