### ISSUE TITLE
Font size of Open Exchange App Description page is too big

### ISSUE THREAD

**Issue by amirsamary** [intersystems-community/openexchange#26]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6372644/55244093-dce0f800-5216-11e9-91fe-c8c34b4f2df5.png">

**Comment by amirsamary** [comment]
The title "HL7 and SMS Interoperability Demo" is unnecessarily big. And this affects the mobile view of it as well.

**Comment by gnibeda** [comment]
done
