### ISSUE TITLE
Version already published error

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/openexchange#266]
Hi,

for the last two times I updated one of my projects, I've been getting an email like this:

> Greetings, Benjamin De Boe
> 
> We received the following error while publishing your package bdb-sql-utils in Package Manager: 
> ERROR #5001: Version 0.3.0 of Package bdb-sql-utils is already published
> Open Exchange Team 

I have no idea what that means, as a little later the updated version, 0.5.2 in this case, gets published fine (hence I didn't bother filing a bug las time)

**Comment by bdeboe** [comment]
Apparently it does *not* get published. When trying to `zpm install` my package, it's still at that 0.3.0 version :-(

**Comment by evshvarov** [comment]
We'll investigate. @bdeboe can you release again with the bumped module.xml version?

**Comment by evshvarov** [comment]
@bdeboe, every new published version should be newer than previous. 
Current version in the module is 0.3.0 https://github.com/bdeboe/isc-sql-utils/blob/195fb15d01a0639c2613322308d50a9b454f7be6/module.xml#L6

**Comment by evshvarov** [comment]
I can also recommend to add in your project module version bumper:
https://github.com/intersystems-community/intersystems-iris-dev-template/blob/master/.github/workflows/bump-module-version.yml
It will increase the module's version with every commit.

**Comment by bdeboe** [comment]
ah, I finally realized I had been neglecting to bump the version number inside module.xml, in addition to what you put into OEX! I'll look into pulling in that automatic bumper next. Thanks!
