### ISSUE TITLE
[minor nit] Right after logging in, some user actions don't work

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/openexchange#268]
(this is only a very minor annoyance that's unlikely to affect many users)

When you only log in _after_ navigating to a package you have edit rights for, the "Settings" and (if you are on the history tab) "Add new release" buttons appear as expected (without fully refreshing the page, it seems), but they don't do anything. 
The actual actions are only enabled for these buttons after refreshing. When you are already logged in before you navigate to the package, everything works as expected.

**Comment by Lena-Ev** [comment]
@bdeboe Benjamin could you please attach one of the screen shots, I suppose you do edits in old way, which will be not available soon, not sure what screen you mean here
