### ISSUE TITLE
[minor nit] Profile page - Github -> GitHub

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#272]
The "h" should be uppercase.

![image](https://github.com/intersystems-community/openexchange/assets/6726799/a5eefd4d-7535-4f11-93d7-3bc92a73c564)

**Comment by Lena-Ev** [comment]
Thank you @gjsjohnmurray
I close this issue here, that will be fixed soon with a new UX/UI.
