### ISSUE TITLE
Tile Logo for Apps with AI features

### ISSUE THREAD

**Issue by alexatwoodhead** [intersystems-community/openexchange#274]
AI is fundamental to emerging software. The Open Exchange should display an AI feature logo on the Application tiles.
![image](https://github.com/intersystems-community/openexchange/assets/691812/798c83fa-9241-4c38-b4b2-4baa8f00ab50)

**Comment by evshvarov** [comment]
Great idea, Alex!
do you know how to distinguish AI enabled startups automatically?

**Comment by alexatwoodhead** [comment]
I think a scan of python classmethods and python source code for "import" and "from" statements, that utilize a known list of AI specific module names could be an approach.
Additionally this will help projects that include python classmethods, yet don't get a "Python" logo.

**Comment by Lena-Ev** [comment]
We discussed this technical possibility and realised  the data fetched maybe not accurate and missleading.
So we suggest to ad another checkmark on app registration: my app utilises AI or ML / or two separate checkmarks.

**Comment by alexatwoodhead** [comment]
Interesting there is opportunity of more than one checkbox:
A few years ago we may have looked at:
* "AI" is an everything superset that includes "ML".
* "ML" contains "DeepLearning"
Therefore checking "AI" would also check "ML", so not that useful.
Last year might have envisioned functional scenarios:
* AI Model Training
* AI Inference - Classificaton, Transcribe
* AI Generative -  Transformer services like LangChain, CoPilot, ChatGPT
Looking at other vendor as-a-service product formulation, can see a pattern that follows more a "Usecase" scenario.
If there were only two checkboxes I would suggest for Open-Exchange:
* IRIS ML - Focused on "Smart Database Tables". Solutions with examples of implementing and configuring classes / tables to be trained by core IRIS product workflow
* Bring-Your-Own ML - Which is focused on developing external Training, Inference and Generative services that are interoperated or otherwise contribute to a solution with IRIS. For example LangChain.

**Comment by Lena-Ev** [comment]
@alexatwoodhead thank you! That looks more like dropdown list, but no problem to implement, will do!

**Comment by Lena-Ev** [comment]
Implemented as tags and filters, as well as the logos for AI and ML

![Image](https://github.com/intersystems-community/openexchange/assets/77621970/b3126792-52bb-46ca-b1c3-6dc986426d73)
