### ISSUE TITLE
Block code rendering problem

### ISSUE THREAD

**Issue by lscalese** [intersystems-community/openexchange#275]
Hi!

I noticed a rendering problem with blocks code in the markdown file (using triple \` char ).

Example with the [web-timing-logger](https://openexchange.intersystems.com/package/web-timing-logger).

The problem occurs only if we use `Use GitHub/GitLab README as long description`, there is no problem if we copy\paste the content of the README.md into the textarea.   Maybe a problem with the request that downloads the README.md on GitHub.

**Comment by gnibeda** [comment]
This is a known issue. It was caused by changing the internal processing of markdown. We will fix it soon.

**Comment by lscalese** [comment]
Hi @gnibeda !

Ok, thank you for the feedback :)

**Comment by isc-rsingh** [comment]
Is this the same problem as YAML being garbled?
See https://openexchange.intersystems.com/package/dbt-iris?tab=details vs. https://github.com/caretdev/dbt-iris/blob/main/README.md

**Comment by Lena-Ev** [comment]
we released the fixes but will check the YAML, will introduce additional fix then

**Comment by MakarovS96** [comment]
https://openexchange.intersystems.com/package/dbt-iris?tab=details 
https://openexchange.intersystems.com/package/FHIR---AI-and-OpenAPI-Chain

**Comment by lscalese** [comment]
It looks good [openapi-suite](https://openexchange.intersystems.com/package/OpenAPI-Suite)
