### ISSUE TITLE
Content-only change submitted for approval incorrectly triggers IPM republish

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#276]
Earlier today I added a link to the description of an app that is configured to publish its releases through IPM. I submitted the change as only an edit, but when I received the email saying it had been approved it was followed by one saying this:

![image](https://github.com/intersystems-community/openexchange/assets/6726799/b487fa4a-e3d5-415a-887f-08fadfe7c9f2)

**Comment by Lena-Ev** [comment]
@gjsjohnmurray please ignore this message for now, we will fix the newsletter so it doesn't send this miss leading message
