### ISSUE TITLE
Text in angle brackets is removed from README.md code blocks

### ISSUE THREAD

**Issue by sduncan01** [intersystems-community/openexchange#278]
Open Exchange application pages can display the README.md from the application's GitHub repository. The README can include Markdown syntax such as code blocks, e.g.

````
```
write ##class(CubeEventMonitor.Utils).Setup(<compileFlags>,<buildCubes>,<updateInterval>,<folderItemResource>,<alertRecipient>)
```
````

which is correctly displayed on GitHub as

```
write ##class(CubeEventMonitor.Utils).Setup(<compileFlags>,<buildCubes>,<updateInterval>,<folderItemResource>,<alertRecipient>)
```

However, if these code blocks include angle brackets, the Open Exchange page removes both the brackets and the text inside them from the README it displays, instead showing something like

```
write ##class(CubeEventMonitor.Utils).Setup(,,,,)
```

This example is from step 3 of the Manual Setup for the CubeEventMonitor: you can compare how it is displayed on [Github](https://github.com/sduncan01/CubeEventMonitor/blob/master/README.md) and on [Open Exchange](https://openexchange.intersystems.com/package/CubeEventMonitor). 

This could be confusing for users reading the setup instructions on Open Exchange. Angle brackets are frequently used in the IRIS documentation, so it seems like it would be helpful to support them in Open Exchange documentation as well.

**Comment by MakarovS96** [comment]
Ask Anton, there is info from backend there

![Image](https://github.com/intersystems-community/openexchange/assets/19629483/07de7c45-49c0-4443-abcb-c737196ee92b)

**Comment by Lena-Ev** [comment]
Tags are still missing for this app although the other app has this issue resolved

**Comment by Lena-Ev** [comment]
Done
