### ISSUE TITLE
use of Docker not detected in some cases

### ISSUE THREAD

**Issue by r-cemper** [intersystems-community/openexchange#280]
I'm checking OEX packages for the existence of  Docker support..
Some cases were not detected if there is no Dockerfile but only 
docker-compose.yaml or docker-compose.yml
examples:
[iris-vector](https://openexchange.intersystems.com/package/iris-vector)
[BeI-MultiModel](https://openexchange.intersystems.com/package/BeI-MultiModel)

**Comment by r-cemper** [comment]
And the next one.  [zbash](https://github.com/nickmitchko/zbash)
Again dynamic docker, no Dockerfile
it's everywhere the same pattern.

**Comment by r-cemper** [comment]
and 3 more
https://openexchange.intersystems.com/package/iris-healthtoolkit-service
https://openexchange.intersystems.com/package/ETL-Interoperability-Adapter
https://openexchange.intersystems.com/package/DevBox

**Comment by MakarovS96** [comment]
Done. Wait for release. Can't detect for iris-vector because it's not indexed by github

**Comment by r-cemper** [comment]
[iris-vector on GitHub](https://github.com/caretdev/iris-vector)
sorry, I don't understand: "not indexed by github"  ??
who / what / where is this indexing done ?
I see **docker-compose.yml** in the repo

**Comment by MakarovS96** [comment]
![Image](https://github.com/intersystems-community/openexchange/assets/19629483/3ed858cf-594b-4c02-a1ce-d7248e4e6920)

I mean I can't use github search api in this repo

**Comment by Lena-Ev** [comment]
Done
