### ISSUE TITLE
flag Docker in OEX directory

### ISSUE THREAD

**Issue by r-cemper** [intersystems-community/openexchange#281]
A simple solution for the few cases that I detected might be 
to set the flag **Docker-available** manually by an OEX_admin,

This might also be useful to signal Docker if the package owner
refuses a related PR  or doesn't update his OEX entry.

Should work to get OEX closer to reality

**Comment by Lena-Ev** [comment]
We have developed an alternative method for searching Docker applications, so the this approach is no longer necessary.

**Comment by r-cemper** [comment]
great, Thanks!
