### ISSUE TITLE
Improve titles of award tiles that represent placings

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#283]
![image](https://github.com/intersystems-community/openexchange/assets/6726799/f305d9a5-5227-4cd0-8d9d-8005e44d5bbc)

Using 1st, 2nd etc would be clearer.

**Comment by Lena-Ev** [comment]
Also in the field of description should be description nit the tutle of the award
![Image](https://github.com/intersystems-community/openexchange/assets/77621970/eea27803-7132-4fd8-b369-0362e0ee956f)

**Comment by Lena-Ev** [comment]
3d
