### ISSUE TITLE
Please allow us to set the date of a new release

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#284]
My InterSystems Server Manager app is a VS Code extension that gets released from GitHub and published on Microsoft Marketplace. I don't always remember to do the "Add new release" procedure (a manual one) on OEX on the same day. When I do it later the OEX release record shows a date that is later than the actual release date.

Please give us the option of setting the release date. Default it to today and allow us to set an earlier date, but require it to be no earlier than the previous release.

**Comment by Lena-Ev** [comment]
approval date - keep as it is (create date) 
release view date - the date that you may assign to your release if it is not the same as create date

To change rests - sort app catalogue, news cataloge etc

**Comment by Lena-Ev** [comment]
- [x] Allow to change the current date (created)
- [x] Check trigger for newsletters by publication(not date) for subscriptions
- [x] Edit old releases 
- [ ] Update design of the form

**Comment by Lena-Ev** [comment]
Send rest to Anton

**Comment by MakarovS96** [comment]
Url="/releases/save" Method="post" реквест добавилось поле approvalDate c датой релиза

**Comment by Lena-Ev** [comment]
@gjsjohnmurray we have introduced the release date field.
If you want to set a date different from the current date just add it to the field and publish your release

**Comment by gjsjohnmurray** [comment]
Thanks!
