### ISSUE TITLE
"Open PRs" notification email has a broken link

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#285]
```html
To view the list of PRs follow <a href=3D"%7B%7Bapp.pr_link%7=
D%7D" style=3D"color: #00A99D;font-weight: 700;text-decoration: none;">this=
 link</a>
```

**Comment by Lena-Ev** [comment]
@gjsjohnmurray Hi John! We have caught this bug and fixed it, if you will have open PRs next month you will recieve the email with the correct link.
currently all the PRs are available under the Pull Requests tab on each app public page
