### ISSUE TITLE
Changing image of Company page didn't require approval

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#32]
After setting up a Company entry for George James Software and getting it approved I used the Upload Image button to add a logo. This worked, and the logo appeared without needing approval. I could also change it again, without needing approval. That's absolutely fine by me, but I'm opening this issue in case you didn't intend it to work that way.

**Comment by MakarovS96** [comment]
Fixed. Please, check.

**Comment by evshvarov** [comment]
@gjsjohnmurray, John! Pinging you if we can close it now

**Comment by gjsjohnmurray** [comment]
I haven't had a reason to verify this, but am happy to take your word for it. Closing.
