### ISSUE TITLE
Please display dates in an unambiguous format

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#35]
I suggest either YYYY-MM-DD or DD-Mmm-YYYY. The first of these is more acceptable internationally because it doesn't month names.

**Comment by evshvarov** [comment]
and remove time? Why do we need the time of publishing? And what's the time belt? )

**Comment by evshvarov** [comment]
@gjsjohnmurray does it work now as expected?

**Comment by gjsjohnmurray** [comment]
LGTM. Closing.
