### ISSUE TITLE
Layout of Company page is unbalanced

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#36]
Here's what ours looks like now there are 4 apps associated with the company:
![image](https://user-images.githubusercontent.com/6726799/56209998-c9be8c80-604c-11e9-8961-f9d85f5799af.png)

Maybe reduce the width of the top block, or centre the area where sets of 3 apps appear, or add spacing between them.

I don't mind the last row being left-justified and incomplete when the number of apps isn't an exact multiple of 3.

**Comment by evshvarov** [comment]
@gjsjohnmurray this is a bug, thanks!

**Comment by gnibeda** [comment]
Yes, this is a bug, because four apps should always fit to company block

**Comment by gnibeda** [comment]
done

**Comment by gjsjohnmurray** [comment]
Nice! Thanks. Closing.
