### ISSUE TITLE
Letters with diacritics are garbled in Details

### ISSUE THREAD

**Issue by adaptun** [intersystems-community/openexchange#43]
Details on following page have word Caché displayed as CachÃ©. Expected that it is displayed as Caché

https://openexchange.intersystems.com/package/Cach%C3%A9-Tortoize-Git

![image](https://user-images.githubusercontent.com/1929255/56493694-9a01ff80-64f8-11e9-811d-d6fcf21ebd9e.png)

**Comment by gnibeda** [comment]
done
