### ISSUE TITLE
Documentation link - where does it appear?

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#44]
I have entered URLs into the Documentation field on my apps, but I don't see where it becomes available you people browsing OEX.

**Comment by evshvarov** [comment]
Looks like we lost it in action) @gnibeda  could you please check? It should be visible on the apps view page

**Comment by gnibeda** [comment]
If possible, please post link to package with issue. It will help me find out what's wrong. Thanks

**Comment by gjsjohnmurray** [comment]
@gnibeda I think all five of the apps at https://openexchange.intersystems.com/company/George-James-Software have documentation URLs, but I don't see a way to visit the doc.

**Comment by gnibeda** [comment]
Yes, now issue is clear. I've fixed it, but you should wait for next deployment of OE to see fixes.

**Comment by gnibeda** [comment]
done

**Comment by gjsjohnmurray** [comment]
Verified. Thanks!
