### ISSUE TITLE
Check/add http/2 support for OpenExchange

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#45]
Could speed up site's performance
Requested by Jon Jonson.
Community supports http/2

**Comment by Lena-Ev** [comment]
$ curl -sI https://openexchange.intersystems.com/ | head -3
HTTP/2 200 
server: nginx/1.17.10
date: Mon, 22 Mar 2021 18:13:49 GMT

$ curl -sI https://partner-dev.community.intersystems.com | head -3
HTTP/2 200 
server: nginx/1.17.10
date: Mon, 22 Mar 2021 18:13:55 GMT
