### ISSUE TITLE
Members page don't work

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#53]
There is an app:
https://openexchange.intersystems.com/package/Dynamic-SQL-to-Dynamic-Object
and his author's page looks like that:
https://openexchange.intersystems.com/user/David%20Crawford/9hr3OE02TC6A0DfkrWQHNLRyE

same for the app:
https://openexchange.intersystems.com/package/Cogs-JSON-Class
Author looks like that:
https://openexchange.intersystems.com/user/Sean%20Connelly/j9s3l7hFYu8HQ124vN0oTX5iumc

**Comment by MakarovS96** [comment]
Done
