### ISSUE TITLE
Change categories design

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#56]
Change category section. 
Introduce "CATEGORY" label - same font as WORKS WITH
Remove Community Supported -> introduce [Category] instead of working as a link

**Comment by evshvarov** [comment]
<img width="387" alt="Screenshot 2019-07-25 14 32 38" src="https://user-images.githubusercontent.com/2781759/61871686-1afed780-aeea-11e9-81b2-a219a3c1f14e.png">

**Comment by MakarovS96** [comment]
Done
