### ISSUE TITLE
Wrong requests should show readable errors

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/openexchange#6]
I/e/ open link https://openexchange.intersystems.com/index.html#!/package/CDV

Should see: No such package exist
Actually see: some error
![image](https://user-images.githubusercontent.com/5127457/48625387-1e87a980-e9c0-11e8-864d-30db0dd52960.png)

**Comment by eduard93** [comment]
Note that package was probably renamed from CDV to IDP-DV

**Comment by eduard93** [comment]
So even better if old urls (before renaming) automatically redirected to a correct url.

**Comment by evshvarov** [comment]
@eduard93 if this is done?

**Comment by eduard93** [comment]
Currently errored URLs redirect to main page. 
Okay, I guess.
