### ISSUE TITLE
Duplicated entry, however it isn't?

### ISSUE THREAD

**Issue by rfns** [intersystems-community/openexchange#60]
Hello, 

I just tried to post one of my project to OpenExchange, but I have been negated with the message that it already exists. So I used the search there to see if there was any occurrence and there wasn't.

The name I used was: Port and port.
The error message was: ERROR #5001: Application with this name already exists.

For now I sent to aproval with the name `port-project` but I would like to change it to `Port` in the future.

**Comment by evshvarov** [comment]
Hi @rfns ! This is fixed! To rename - unpublish it, rename and send for approval again.
Also you may want to connect the app with the related article on DC - the button Discuss will be active then

**Comment by rfns** [comment]
Good to know, I have sent another approval request with an updated version of the project. I'll think of a way to explain the usage and update that old article as well, it might be even better if I create a new one.
