### ISSUE TITLE
Add syntax highlight for ObjectScript language

### ISSUE THREAD

**Issue by rfns** [intersystems-community/openexchange#63]

**Comment by evshvarov** [comment]
What do you mean @rfns ?
There is ObjectScript syntax highlight in Github: https://community.intersystems.com/post/github-now-supports-objectscript

**Comment by rfns** [comment]
If you type a description using markdown on OpenExchange the code won't have the syntax highlight even if you type it as:

```
```objectscript
ClassMethod SyntaxHighlight()
{
}```
```

Check the project description I put in the [Frontier](https://openexchange.intersystems.com/package/Frontier) project you'll notice that none of my code is highlighted, since it's all black text.

But if you check my [README](https://github.com/rfns/frontier) you'll notice that the code is highlighted on GitHub.

**Comment by evshvarov** [comment]
@rfns , I don't know how to support it.  @daimor, do you know if this possible?
But I invite you to repost the readme as an article on [InterSystems Developers](community.intersystems.com) - it supports ObjectScript highlighting nicely.

**Comment by daimor** [comment]
I have to do some research

**Comment by rfns** [comment]
Wouldn't it be possible to use the same markdown library that is being used for the Community forums?

**Comment by daimor** [comment]
I think in this case would be better to use the same view as on GitHub
Don't you agree?

**Comment by rfns** [comment]
Yes, if you can use Linguist for that, that would be nice.

**Comment by daimor** [comment]
@evshvarov GitHub has an [API request](https://developer.github.com/v3/markdown/) which converts Markdown to HTML. And it works with ObjectScript too

**Comment by gnibeda** [comment]
We can't rely on github API for such tasks because of rate limit:
[https://developer.github.com/v3/rate_limit/](https://developer.github.com/v3/rate_limit/)
50 requests per hour for unauthorized and 5000 for authorized requests

**Comment by daimor** [comment]
Readme not changing so fast, so, if it did not change, just keep the previous render.

**Comment by gnibeda** [comment]
This is already planed, as I told in telegram chennel. But @evshvarov said that for now we have more urgent tasks. 
Anyway this is backed related issue and @MakarovS96 is too busy now for it implementation.

**Comment by bdeboe** [comment]
I was about to file a separate issue about emojis supported in github markdown not showing up on OpenExchange renderings (e.g. the use of :warning: on https://openexchange.intersystems.com/package/IRIS-memory-configuration-wizard), but guess that would be handled by the same change as this one?

**Comment by bdeboe** [comment]
and it would be great if this would also address #62

**Comment by Lena-Ev** [comment]
done
