### ISSUE TITLE
DC profile link is unvalidated

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#64]
The newly-introduced "Community Profile" field seems to accept a URL that isn't a DC profile page. Is this intentional? If so, is it wise?

**Comment by evshvarov** [comment]
Thanks for mentioning it, @gjsjohnmurray. We don't expect people who have approved solutions to introduce any spam to this field. Also, we plan to use the DC API later for this - but you can benefit from the linkage even now.

**Comment by MakarovS96** [comment]
Done. Now we get DC Profile link for users directly from DC!
