### ISSUE TITLE
Links as links without Javascript

### ISSUE THREAD

**Issue by daimor** [intersystems-community/openexchange#8]
All links should work as links, without javascript.
When I want to open some package or any link in another tab, it does not work.
in macOS, I usually use cmd+click on a link, to open link in new tab, and this action reloads a page.

**Comment by evshvarov** [comment]
@daimor if it is done?

**Comment by daimor** [comment]
Nope, nothing was changed here.
I still can't open any package or any other page in another tab, from the context menu, or my cmd+click

**Comment by gnibeda** [comment]
This is known issue, will fix it soon

**Comment by evshvarov** [comment]
Could we close it?
