### ISSUE TITLE
Remove Arial MT from site

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/openexchange#86]
replace with what is used in item description pages (we should remove the Emoji fonts from this CSS everywhere it appears):
``` css
font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
```

**Comment by evshvarov** [comment]
@rajrsingh , could you please close if this is fixed?
