### ISSUE TITLE
Better URL for pages

### ISSUE THREAD

**Issue by daimor** [intersystems-community/openexchange#9]
Please do not use hash mark in the URLs, much better to use more readable direct urls.

like 
https://openexchange.intersystems.com/package/DSW-Reports
instead of
https://openexchange.intersystems.com/index.html#!/package/DSW-Reports

and
https://openexchange.intersystems.com/product/Caché
instead of
https://openexchange.intersystems.com/index.html#!/product/Caché

**Comment by evshvarov** [comment]
@daimor guess it's done?
