### ISSUE TITLE
Show the status of the App for a Developer VERY EVIDENT

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#97]
Like A stamp:
![published](https://user-images.githubusercontent.com/2781759/72217625-a1af7b80-3541-11ea-989a-2fa2c823856a.png)

![pending](https://user-images.githubusercontent.com/2781759/72217627-a70cc600-3541-11ea-9618-8c66a598ccd7.png)

![draft](https://user-images.githubusercontent.com/2781759/72217628-ab38e380-3541-11ea-8557-bdf4907ee2f2.jpeg)

And the comment for each stage is:

Published: 
"Your app is published, everybody is seeing it and can use it! But you can make a new release with Settings->Edit."

Pending: 
"Your app is on review. Take a deep breath and wait a bit more. You'll be notified in numerous places!"

Draft:
"You are editing your app. Nobody is seeing it, it's only you. Once you are ready and happy click on Settings->Send for Approval to publish it"

**Comment by gnibeda** [comment]
Need design for it
